# -*- coding: utf-8 -*-
"""
Automatically generated by manage.py config -m 
/!\ This file should only used in development mode
Python local configuration (os.environ["DJANGOFLOOR_PYTHON_SETTINGS"]) = /Users/flanker/.virtualenvs/moneta34/etc/moneta/settings.py
INI local configuration (os.environ["DJANGOFLOOR_INI_SETTINGS"]) = /Users/flanker/.virtualenvs/moneta34/etc/moneta/settings.ini
Default project settings (os.environ["DJANGOFLOOR_PROJECT_DEFAULTS"]) = /Users/flanker/Developer/Github/Moneta/moneta/defaults.py
Other default settings = /Users/flanker/Developer/Github/DjangoFloor/djangofloor/defaults.py
"""
from __future__ import unicode_literals
# This line allows to add values only in /Users/flanker/Developer/Github/Moneta/moneta/defaults.p

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[localhost] '
ACCOUNT_EMAIL_VERIFICATION = None
ADMINS = (('admin', 'admin@localhost'),)
ADMIN_EMAIL = 'admin@localhost'
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ARCHIVE_FILTERS = ['moneta.repository.filters.informations']
AUTHENTICATION_BACKENDS = ['djangofloor.backends.DefaultGroupRemoteUserBackend',
                           'django.contrib.auth.backends.ModelBackend',
                           'allauth.account.auth_backends.AuthenticationBackend']
BIND_ADDRESS = '127.0.0.1:8131'
BOOTSTRAP3 = {'jquery_url': '/static/js/jquery.min.js', 'javascript_url': None, 'horizontal_label_class': 'col-md-4',
              'horizontal_field_class': 'col-md-8', 'base_url': '/static/bootstrap3/', 'theme_url': None,
              'css_url': None}
BROKER_DB = 13
BROKER_URL = 'redis://localhost:6379/13'
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.dummy.DummyCache'}}
CACHE_BACKEND = 'django.core.cache.backends.dummy.DummyCache'
CELERY_ACCEPT_CONTENT = ['json', 'yaml', 'msgpack']
CELERY_APP = 'djangofloor'
CELERY_CREATE_DIRS = True
CELERY_RESULT_EXCHANGE = 'moneta_results'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Paris'
CONN_MAX_AGE = 600
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False
DATABASES = {'default': {'USER': '', 'PASSWORD': '', 'ATOMIC_REQUESTS': False, 'TIME_ZONE': None,
                         'TEST': {'NAME': None, 'COLLATION': None, 'CHARSET': None, 'MIRROR': None}, 'HOST': '',
                         'NAME': './django_data/data/database.sqlite3', 'OPTIONS': {}, 'AUTOCOMMIT': True,
                         'CONN_MAX_AGE': 0, 'PORT': '', 'ENGINE': 'django.db.backends.sqlite3'}}
DATABASE_ENGINE = 'django.db.backends.sqlite3'
DATABASE_HOST = ''
DATABASE_NAME = './django_data/data/database.sqlite3'
DATABASE_PASSWORD = ''
DATABASE_PORT = ''
DATABASE_USER = ''
DATA_PATH = './django_data/data'
DEBUG = True
DEBUG_TOOLBAR_CONFIG = {'JQUERY_URL': None}
DEBUG_TOOLBAR_PANELS = ['debug_toolbar.panels.versions.VersionsPanel', 'debug_toolbar.panels.timer.TimerPanel',
                        'debug_toolbar.panels.profiling.ProfilingPanel', 'debug_toolbar.panels.settings.SettingsPanel',
                        'debug_toolbar.panels.headers.HeadersPanel', 'debug_toolbar.panels.request.RequestPanel',
                        'debug_toolbar.panels.sql.SQLPanel', 'debug_toolbar.panels.staticfiles.StaticFilesPanel',
                        'debug_toolbar.panels.templates.TemplatesPanel', 'debug_toolbar.panels.cache.CachePanel',
                        'debug_toolbar.panels.signals.SignalsPanel', 'debug_toolbar.panels.redirects.RedirectsPanel']
DEBUG_TOOLBAR_PATCH_SETTINGS = False
DEFAULT_CHARSET = 'utf-8'
DEFAULT_CONTENT_TYPE = 'text/html'
DEFAULT_FROM_EMAIL = 'admin@localhost'
EMAIL_SUBJECT_PREFIX = '[Moneta / localhost] '
FILE_CHARSET = 'utf-8'
FILE_UPLOAD_TEMP_DIR = None
FLOOR_AUTHENTICATION_HEADER = 'HTTP_REMOTE_USER'
FLOOR_BACKUP_SINGLE_TRANSACTION = False
FLOOR_DEFAULT_GROUP_NAME = 'Users'
FLOOR_EXTRA_APPS = []
FLOOR_EXTRA_CSS = []
FLOOR_EXTRA_JS = []
FLOOR_FAKE_AUTHENTICATION_GROUPS = ['group1', 'group2']
FLOOR_FAKE_AUTHENTICATION_USERNAME = None
FLOOR_INDEX = 'moneta.views.index'
FLOOR_INSTALLED_APPS = ['moneta', 'moneta.repositories', 'moneta.repository']
FLOOR_PROJECT_NAME = 'Moneta'
FLOOR_PROJECT_VERSION = '1.7.7'
FLOOR_SIGNAL_DECODER = 'json.JSONDecoder'
FLOOR_SIGNAL_ENCODER = 'django.core.serializers.json.DjangoJSONEncoder'
FLOOR_TEMPLATE_CONTEXT_PROCESSORS = []
FLOOR_URL_CONF = 'moneta.root_urls.urls'
FLOOR_USE_WS4REDIS = False
FLOOR_WS_FACILITY = 'djangofloor'
GNUPG_HOME = './django_data/gpg'
GNUPG_KEYID = '1DA759EA7F5EF06F'
GNUPG_PATH = 'gpg'
INSTALLED_APPS = ['django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions',
                  'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.humanize',
                  'django.contrib.sites', 'django.contrib.sitemaps', 'django.contrib.admin', 'djangofloor',
                  'bootstrap3', 'allauth', 'allauth.account', 'allauth.socialaccount', 'pipeline', 'debug_toolbar',
                  'moneta', 'moneta.repositories', 'moneta.repository']
INTERNAL_IPS = ('127.0.0.1',)
LANGUAGE_CODE = 'fr-fr'
LOCAL_PATH = './django_data'
LOGGING = {'filters': {'require_debug_true': {'()': 'django.utils.log.RequireDebugTrue'},
                       'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'}}, 'version': 1, 'handlers': {
    'stream': {'level': 'WARNING', 'filters': ['require_debug_false'], 'class': 'logging.StreamHandler'},
    'debug': {'level': 'DEBUG', 'filters': ['require_debug_true'], 'class': 'logging.StreamHandler'},
    'mail_admins': {'level': 'ERROR', 'filters': ['require_debug_false'], 'class': 'djangofloor.log.FloorAdminEmailHandler',
                    'min_interval': 600}},
           'loggers': {'django.request': {'level': 'ERROR', 'handlers': ['stream', 'mail_admins'], 'propagate': False},
                       'djangofloor.signals': {'level': 'DEBUG', 'handlers': ['debug'], 'propagate': False}},
           'disable_existing_loggers': True}
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
LOGOUT_URL = '/accounts/logout/'
LOG_PATH = './django_data/log'
MANAGERS = (('admin', 'admin@localhost'),)
MAX_REQUESTS = 10000
MEDIA_ROOT = './django_data/data/media'
MEDIA_URL = '/media/'
MIDDLEWARE_CLASSES = ['django.middleware.cache.UpdateCacheMiddleware', 'django.middleware.common.CommonMiddleware',
                      'debug_toolbar.middleware.DebugToolbarMiddleware',
                      'django.contrib.sessions.middleware.SessionMiddleware',
                      'django.middleware.csrf.CsrfViewMiddleware', 'django.middleware.security.SecurityMiddleware',
                      'django.contrib.auth.middleware.AuthenticationMiddleware',
                      'django.contrib.messages.middleware.MessageMiddleware',
                      'django.middleware.clickjacking.XFrameOptionsMiddleware', 'djangofloor.middleware.IEMiddleware',
                      'djangofloor.middleware.RemoteUserMiddleware', 'djangofloor.middleware.BasicAuthMiddleware',
                      'djangofloor.middleware.FakeAuthenticationMiddleware',
                      'django.middleware.cache.FetchFromCacheMiddleware']
OTHER_ALLAUTH = []
PIPELINE = {'PIPELINE_ENABLED': False, 'MIMETYPES': (
    (b'text/coffeescript', '.coffee'), (b'text/less', '.less'), (b'text/javascript', '.js'), (b'text/x-sass', '.sass'),
    (b'text/x-scss', '.scss')), 'STYLESHEETS': {
    'default': {'extra_context': {'media': 'all'}, 'output_filename': 'css/default.css',
                'source_filenames': ['bootstrap3/css/bootstrap.min.css', 'css/font-awesome.min.css',
                                     'css/bootstrap-select.min.css', 'css/djangofloor.css']}}, 'JS_COMPRESSOR': None,
            'CSS_COMPRESSOR': 'djangofloor.middleware.RCSSMinCompressor', 'JAVASCRIPT': {
    'ie9': {'output_filename': 'js/ie9.js', 'source_filenames': ['js/html5shiv.js', 'js/respond.min.js']},
    'default': {'output_filename': 'js/default.js',
                'source_filenames': ['js/jquery.min.js', 'bootstrap3/js/bootstrap.min.js', 'js/bootstrap-notify.min.js',
                                     'js/djangofloor.js', 'js/bootstrap-select.min.js', 'js/ws4redis.js']}}}
PIPELINE_CSS = {'default': {'extra_context': {'media': 'all'}, 'output_filename': 'css/default.css',
                            'source_filenames': ['bootstrap3/css/bootstrap.min.css', 'css/font-awesome.min.css',
                                                 'css/bootstrap-select.min.css', 'css/djangofloor.css']}}
PIPELINE_CSS_COMPRESSOR = 'djangofloor.middleware.RCSSMinCompressor'
PIPELINE_ENABLED = False
PIPELINE_JS = {'ie9': {'output_filename': 'js/ie9.js', 'source_filenames': ['js/html5shiv.js', 'js/respond.min.js']},
               'default': {'output_filename': 'js/default.js',
                           'source_filenames': ['js/jquery.min.js', 'bootstrap3/js/bootstrap.min.js',
                                                'js/bootstrap-notify.min.js', 'js/djangofloor.js',
                                                'js/bootstrap-select.min.js', 'js/ws4redis.js']}}
PIPELINE_JS_COMPRESSOR = None
PIPELINE_MIMETYPES = (
    (b'text/coffeescript', '.coffee'), (b'text/less', '.less'), (b'text/javascript', '.js'), (b'text/x-sass', '.sass'),
    (b'text/x-scss', '.scss'))
PROJECT_NAME = 'moneta'
PROTOCOL = 'http'
RAVEN_CONFIG = {'dsn': '', 'release': '1.7.7'}
REDIS_HOST = 'localhost'
REDIS_PORT = '6379'
REPOSITORY_CLASSES = ['moneta.repositories.aptitude.Aptitude', 'moneta.repositories.pypi.Pypi',
                      'moneta.repositories.maven3.Maven3', 'moneta.repositories.flat_files.FlatFile',
                      'moneta.repositories.yum.Yum', 'moneta.repositories.ruby.RubyGem',
                      'moneta.repositories.jetbrains.Jetbrains',
                      'moneta.repositories.vagrant.Vagrant', ]
REVERSE_PROXY_IPS = ['127.0.0.1']
REVERSE_PROXY_PORT = None
REVERSE_PROXY_SSL_CRT_FILE = None
REVERSE_PROXY_SSL_KEY_FILE = None
REVERSE_PROXY_TIMEOUT = 300
ROOT_URLCONF = 'djangofloor.root_urls'
SECRET_KEY = 'NEZ6ngWX0JihNG2wepl1uxY7bkPOWrTEo27vxPGlUM3eBAYfPT'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False
SENTRY_DSN_URL = ''
SERVER_EMAIL = 'root@localhost'
SERVER_NAME = 'localhost'
SESSION_COOKIE_SECURE = False
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SITE_ID = 1
STATICFILES_DIRS = []
STATICFILES_FINDERS = ['django.contrib.staticfiles.finders.AppDirectoriesFinder',
                       'django.contrib.staticfiles.finders.FileSystemFinder', 'pipeline.finders.PipelineFinder']
STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'
STATIC_ROOT = './django_data/static'
STATIC_URL = '/static/'
STORAGES = {'archive': {'ROOT': './django_data/data/media/archives', 'ENGINE': 'moneta.repository.storages.FlatStorage',
                        'PATH_LEN': 1},
            'cache': {'ROOT': './django_data/data/media/cache', 'ENGINE': 'moneta.repository.storages.FlatStorage',
                      'PATH_LEN': 1}, 'default': {'ROOT': './django_data/data/media/uncompressed',
                                                  'ENGINE': 'moneta.repository.storages.FlatStorage', 'PATH_LEN': 1}}
STORAGE_ARCHIVE = 'archive'
STORAGE_CACHE = 'cache'
STORAGE_UNCOMPRESSED = 'uncompressed'
TEMPLATES = [{'APP_DIRS': True, 'DIRS': [], 'OPTIONS': {
    'context_processors': ['django.contrib.auth.context_processors.auth', 'django.core.context_processors.debug',
                           'django.core.context_processors.request', 'django.core.context_processors.i18n',
                           'django.core.context_processors.media', 'django.core.context_processors.static',
                           'django.core.context_processors.tz', 'django.contrib.messages.context_processors.messages',
                           'djangofloor.context_processors.context_base', 'moneta.context_processors.context_base',
                           'django.template.context_processors.request']},
              'BACKEND': 'django.template.backends.django.DjangoTemplates'}]
TEMP_ROOT = './django_data/tmp'
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
THREADS = 1
TIME_ZONE = 'Europe/Paris'
UPLOAD_ROOT = 'uploads'
USE_CELERY = False
USE_I18N = True
USE_L10N = True
USE_SCSS = False
USE_TZ = True
USE_X_FORWARDED_HOST = True
USE_X_SEND_FILE = False
WEBSOCKET_URL = '/ws/'
WORKERS = 1
WS4REDIS_CONNECTION = {'db': 15, 'port': '6379', 'host': 'localhost'}
WS4REDIS_DB = 15
WS4REDIS_EMULATION_INTERVAL = 0
WS4REDIS_EXPIRE = 0
WS4REDIS_HEARTBEAT = '--HEARTBEAT--'
WS4REDIS_PREFIX = 'ws'
WS4REDIS_SUBSCRIBER = 'djangofloor.df_ws4redis.Subscriber'
WSGI_APPLICATION = 'djangofloor.wsgi_http.application'
X_ACCEL_REDIRECT = []
X_FRAME_OPTIONS = 'SAMEORIGIN'
